-- Baseline schema generated from the Entity mappings at commit
-- 18f046aca81535e24046750db65829fb041820a5.
--
-- Empty databases execute this migration. Existing populated schemas must be
-- backed up and explicitly baselined at version 1 before Hibernate validation.
create table bookmarks (content_item_id bigint not null, created_at datetime(6), id bigint not null auto_increment, user_account_id bigint not null, primary key (id)) engine=InnoDB;
create table categories (id bigint not null auto_increment, name varchar(120) not null, slug varchar(120) not null, primary key (id)) engine=InnoDB;
create table content_item_categories (category_id bigint not null, content_item_id bigint not null, primary key (category_id, content_item_id)) engine=InnoDB;
create table content_item_levels (content_item_id bigint not null, level_id bigint not null, primary key (content_item_id, level_id)) engine=InnoDB;
create table content_items (published bit not null, id bigint not null auto_increment, reviewed_at datetime(6), slug varchar(120) not null, source_ref varchar(160), review_note varchar(1000), review_status enum ('APPROVED','PENDING','REJECTED'), type enum ('GRAMMAR','WORD') not null, primary key (id)) engine=InnoDB;
create table content_review_history (content_item_id bigint not null, id bigint not null auto_increment, reviewed_at datetime(6) not null, reviewer_id bigint, note varchar(1000), previous_status enum ('APPROVED','PENDING','REJECTED'), status enum ('APPROVED','PENDING','REJECTED') not null, primary key (id)) engine=InnoDB;
create table content_sources (id bigint not null auto_increment, version varchar(80), source_ref varchar(160) not null, display_name varchar(200) not null, license_summary varchar(500), license_url varchar(500), usage_note varchar(1000), attribution varchar(2000), primary key (id)) engine=InnoDB;
create table curation_review_history (id bigint not null auto_increment, record_id bigint not null, reviewed_at datetime(6) not null, reviewer_id bigint not null, note varchar(1000), previous_status enum ('APPROVED','PENDING','REJECTED'), record_type enum ('COMPARISON','CONFIRMATION','ENRICHMENT','RELATION') not null, status enum ('APPROVED','PENDING','REJECTED') not null, primary key (id)) engine=InnoDB;
create table email_verification_tokens (created_at datetime(6) not null, expires_at datetime(6) not null, id bigint not null auto_increment, used_at datetime(6), user_account_id bigint not null, token_hash varchar(64) not null, primary key (id)) engine=InnoDB;
create table examples (display_order integer not null, content_item_id bigint not null, id bigint not null auto_increment, meaning_id bigint, japanese_text varchar(1000) not null, reading varchar(1000), translation varchar(1000), search_key varchar(2500), audio_file_name varchar(255), primary key (id)) engine=InnoDB;
create table grammar_comparisons (published bit not null, review_status tinyint not null, grammar_relation_id bigint not null, id bigint not null auto_increment, reviewed_at datetime(6), source_ref varchar(300) not null, common_confusion varchar(3000), key_difference varchar(3000), summary varchar(3000), usage_difference varchar(3000), primary key (id)) engine=InnoDB;
create table grammar_confirmation_attempts (answered_at datetime(6) not null, id bigint not null auto_increment, learner_profile_id bigint not null, question_id bigint not null, result enum ('CORRECT','INCORRECT') not null, primary key (id)) engine=InnoDB;
create table grammar_confirmation_choices (correct_answer bit not null, display_order integer not null, id bigint not null auto_increment, question_id bigint not null, choice_text varchar(1000) not null, primary key (id)) engine=InnoDB;
create table grammar_confirmation_questions (published bit not null, review_status tinyint not null, grammar_id bigint not null, id bigint not null auto_increment, reviewed_at datetime(6), source_ref varchar(300) not null, context varchar(3000), explanation varchar(3000), prompt varchar(3000) not null, question_type enum ('CONTEXT_GAP','MEANING_MATCH','RELATION_CHOICE') not null, primary key (id)) engine=InnoDB;
create table grammar_enrichments (published bit not null, review_status tinyint not null, grammar_id bigint not null, id bigint not null auto_increment, reviewed_at datetime(6), source_ref varchar(300) not null, common_mistake varchar(3000), formation_supplement varchar(3000), learner_note varchar(3000), nuance varchar(3000), usage_note varchar(3000), primary key (id)) engine=InnoDB;
create table grammar_relations (published bit not null, review_status tinyint not null, id bigint not null auto_increment, left_grammar_id bigint not null, reviewed_at datetime(6), right_grammar_id bigint not null, source_ref varchar(300) not null, relation_type enum ('CONFUSABLE','CONTRAST','SIMILAR') not null, primary key (id)) engine=InnoDB;
create table grammars (content_item_id bigint not null, id bigint not null auto_increment, pattern varchar(200) not null, pattern_search varchar(200), connection varchar(500), explanation varchar(2000) not null, search_text varchar(2500), primary key (id)) engine=InnoDB;
create table imported_source_records (content_item_id bigint, id bigint not null auto_increment, source_note_id bigint not null, level_code varchar(20), note_type varchar(120) not null, source_ref varchar(160) not null, tags varchar(1000) not null, field_names longtext not null, field_values longtext not null, primary key (id)) engine=InnoDB;
create table learner_preference_categories (category_id bigint not null, preference_id bigint not null, primary key (category_id, preference_id)) engine=InnoDB;
create table learner_preference_levels (level_id bigint not null, preference_id bigint not null, primary key (level_id, preference_id)) engine=InnoDB;
create table learner_profiles (daily_goal integer, experience integer not null, onboarding_completed bit, created_at datetime(6) not null, id bigint not null auto_increment, last_studied_at datetime(6), onboarding_completed_at datetime(6), updated_at datetime(6) not null, user_account_id bigint, pending_growth_stage_key varchar(40), presented_growth_stage_key varchar(40), character_key varchar(80) not null, display_name varchar(120) not null, learner_key varchar(120) not null, primary key (id)) engine=InnoDB;
create table learner_study_preferences (daily_new_grammar_limit integer, daily_new_word_limit integer, reminder_enabled bit, reminder_time time(0), id bigint not null auto_increment, learner_profile_id bigint not null, primary key (id)) engine=InnoDB;
create table learning_progress (consecutive_correct int default 0 not null, lapse_count int default 0 not null, review_count integer not null, content_item_id bigint not null, id bigint not null auto_increment, last_studied_at datetime(6) not null, learner_profile_id bigint not null, next_review_at datetime(6) not null, last_result enum ('CORRECT','INCORRECT') not null, learning_state varchar(20) default 'LEARNING', primary key (id)) engine=InnoDB;
create table learning_streaks (current_streak integer not null, last_activity_date date, longest_streak integer not null, id bigint not null auto_increment, learner_profile_id bigint not null, primary key (id)) engine=InnoDB;
create table levels (id bigint not null auto_increment, code varchar(40) not null, level_system varchar(40) not null, name varchar(120) not null, primary key (id)) engine=InnoDB;
create table meanings (sense_order integer not null, id bigint not null auto_increment, word_id bigint not null, language_tag varchar(10) not null, search_key varchar(500), text varchar(500) not null, primary key (id)) engine=InnoDB;
create table password_reset_tokens (created_at datetime(6) not null, expires_at datetime(6) not null, id bigint not null auto_increment, used_at datetime(6), user_account_id bigint not null, token_hash varchar(64) not null, primary key (id)) engine=InnoDB;
create table quiz_attempts (earned_experience integer not null, streak_eligible bit, answered_at datetime(6) not null, id bigint not null auto_increment, learner_profile_id bigint not null, question_source_record_id bigint not null, result enum ('CORRECT','INCORRECT') not null, primary key (id)) engine=InnoDB;
create table quiz_session_items (answered bit not null, correct bit, earned_experience integer not null, position integer not null, answered_at datetime(6), content_item_id bigint not null, id bigint not null auto_increment, session_id bigint not null, instruction varchar(300) not null, correct_answer varchar(2000) not null, submitted_answer varchar(2000), choices_json tinytext, explanation tinytext, prompt tinytext not null, question_type enum ('GRAMMAR_CONTEXT_CHOICE','GRAMMAR_MEANING_TO_PATTERN','GRAMMAR_PATTERN_TO_MEANING','WORD_JAPANESE_TO_MEANING','WORD_MEANING_TO_JAPANESE','WORD_READING_CHOICE','WORD_READING_INPUT') not null, primary key (id)) engine=InnoDB;
create table quiz_sessions (answered_count integer not null, correct_count integer not null, earned_experience integer not null, total_questions integer not null, completed_at datetime(6), id bigint not null auto_increment, learner_profile_id bigint not null, started_at datetime(6) not null, public_id varchar(36) not null, session_key varchar(120) not null, mode enum ('QUICK') not null, state enum ('ACTIVE','COMPLETED') not null, primary key (id)) engine=InnoDB;
create table study_collection_items (content_item_id bigint not null, created_at datetime(6), id bigint not null auto_increment, study_collection_id bigint not null, primary key (id)) engine=InnoDB;
create table study_collections (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, user_account_id bigint not null, name varchar(80) not null, primary key (id)) engine=InnoDB;
create table study_queue_entries (content_item_id bigint not null, created_at datetime(6), id bigint not null auto_increment, user_account_id bigint not null, primary key (id)) engine=InnoDB;
create table study_records (content_item_id bigint not null, id bigint not null auto_increment, learner_profile_id bigint not null, studied_at datetime(6) not null, session_key varchar(120), activity_type enum ('NEW','RETRAIN','REVIEW'), result enum ('CORRECT','INCORRECT') not null, primary key (id)) engine=InnoDB;
create table today_study_session_items (completed bit not null, position integer not null, completed_at datetime(6), content_item_id bigint not null, id bigint not null auto_increment, session_id bigint not null, planned_activity_type enum ('NEW','RETRAIN','REVIEW') not null, result enum ('CORRECT','INCORRECT'), primary key (id)) engine=InnoDB;
create table today_study_sessions (planned_new_grammar_count integer not null, planned_new_word_count integer not null, planned_review_count integer not null, session_date date not null, completed_at datetime(6), created_at datetime(6) not null, id bigint not null auto_increment, learner_profile_id bigint not null, session_key varchar(120) not null, state enum ('ACTIVE','COMPLETED') not null, primary key (id)) engine=InnoDB;
create table user_accounts (email_verified bit, id bigint not null auto_increment, joined_at datetime(6) not null, display_name varchar(80) not null, login_id varchar(80) not null, password_hash varchar(100) not null, email varchar(160), role enum ('ADMIN','USER') not null, primary key (id)) engine=InnoDB;
create table weakness_review_session_items (completed bit not null, position integer not null, completed_at datetime(6), content_item_id bigint not null, id bigint not null auto_increment, session_id bigint not null, primary key (id)) engine=InnoDB;
create table weakness_review_sessions (completed_at datetime(6), created_at datetime(6) not null, id bigint not null auto_increment, learner_profile_id bigint not null, session_key varchar(120) not null, state enum ('ACTIVE','COMPLETED') not null, primary key (id)) engine=InnoDB;
create table words (content_item_id bigint not null, id bigint not null auto_increment, expression varchar(120) not null, expression_search varchar(120), part_of_speech varchar(120), reading varchar(120) not null, reading_search varchar(120), pitch_accent varchar(500), primary key (id)) engine=InnoDB;
alter table bookmarks add constraint uk_bookmark_user_content unique (user_account_id, content_item_id);
alter table categories add constraint UKoul14ho7bctbefv8jywp5v3i2 unique (slug);
create index idx_content_published_type on content_items (published, type);
alter table content_items add constraint UKgqkchofk6igo2uk78bhdmxc9l unique (slug);
alter table content_sources add constraint UK57isy6ep3bb0xmscdtc4qjx6l unique (source_ref);
create index idx_curation_history_target on curation_review_history (record_type, record_id, reviewed_at);
create index idx_email_verification_user_created on email_verification_tokens (user_account_id, created_at);
alter table email_verification_tokens add constraint idx_email_verification_token_hash unique (token_hash);
alter table grammar_comparisons add constraint UKllpdvxsvhg2mfu8qgkfqt60g5 unique (grammar_relation_id);
alter table grammar_enrichments add constraint UKnchkny7vngg78i60vbv696f6y unique (grammar_id);
alter table grammar_relations add constraint uk_grammar_relation_pair_type unique (left_grammar_id, right_grammar_id, relation_type);
create index idx_grammar_pattern_search on grammars (pattern_search);
alter table grammars add constraint UK8478riywbov01txd8hsukcu2n unique (content_item_id);
alter table imported_source_records add constraint uk_imported_source_record unique (source_ref, note_type, source_note_id);
alter table learner_profiles add constraint UK8ouphn6mwwvdc8uug3gnvpde3 unique (user_account_id);
alter table learner_profiles add constraint UK72yosf2grpuhy8ab6odeyyi9x unique (learner_key);
alter table learner_study_preferences add constraint UK24svq498wuih61se9v94a6n4u unique (learner_profile_id);
alter table learning_progress add constraint uk_learning_progress_learner_content unique (learner_profile_id, content_item_id);
alter table learning_streaks add constraint UK6bfogxjj6meih4epe3gvp8dv6 unique (learner_profile_id);
create index idx_password_reset_user_created on password_reset_tokens (user_account_id, created_at);
alter table password_reset_tokens add constraint idx_password_reset_token_hash unique (token_hash);
alter table quiz_session_items add constraint uk_quiz_session_position unique (session_id, position);
create index idx_quiz_session_owner_state on quiz_sessions (learner_profile_id, state);
alter table quiz_sessions add constraint UKsq1080a3htgmef4a5gdevcmdi unique (public_id);
alter table quiz_sessions add constraint UK7sgan72w2g0q2ertorbdfx0hc unique (session_key);
alter table study_collection_items add constraint uk_study_collection_content unique (study_collection_id, content_item_id);
alter table study_queue_entries add constraint uk_study_queue_user_content unique (user_account_id, content_item_id);
alter table study_records add constraint uk_study_session_content unique (learner_profile_id, session_key, content_item_id);
alter table today_study_session_items add constraint uk_today_session_position unique (session_id, position);
alter table today_study_session_items add constraint uk_today_session_content unique (session_id, content_item_id);
alter table today_study_sessions add constraint uk_today_study_session_learner_date unique (learner_profile_id, session_date);
alter table today_study_sessions add constraint UKr7g7cy7saoas26dcekknuwcyc unique (session_key);
alter table user_accounts add constraint UKpffekdvjpp64rkath1gjnjhmx unique (login_id);
alter table user_accounts add constraint UKf9sl209luxhu4rylls0h1m625 unique (email);
alter table weakness_review_session_items add constraint uk_weakness_session_position unique (session_id, position);
alter table weakness_review_session_items add constraint uk_weakness_session_content unique (session_id, content_item_id);
alter table weakness_review_sessions add constraint UKpuco421t7ergui94fnfeh389 unique (session_key);
create index idx_word_expression_search on words (expression_search);
create index idx_word_reading_search on words (reading_search);
alter table words add constraint UK6px2bj5h5xx1tvyag8e7st4af unique (content_item_id);
alter table bookmarks add constraint FKidxvoc5ou4dvwka8as46wv6of foreign key (content_item_id) references content_items (id);
alter table bookmarks add constraint FK4wsdvs3750guatd3w94xyg0jo foreign key (user_account_id) references user_accounts (id);
alter table content_item_categories add constraint FKj37d6769jiwns8skdcda3o4ld foreign key (category_id) references categories (id);
alter table content_item_categories add constraint FK6cnfi3055y7k7ovkfs0p6a9gn foreign key (content_item_id) references content_items (id);
alter table content_item_levels add constraint FK18vply8jmlhflxi2btt01xqpa foreign key (level_id) references levels (id);
alter table content_item_levels add constraint FK2pl4rfka8etk9ssduvllq68uq foreign key (content_item_id) references content_items (id);
alter table content_review_history add constraint FK50xhfxgq1getp6qfer6eo992o foreign key (content_item_id) references content_items (id);
alter table content_review_history add constraint FKl48q4nelb9nyw433sr4sd8ch foreign key (reviewer_id) references user_accounts (id);
alter table curation_review_history add constraint FKfr1hda002vuk0w3khjk1cr1p7 foreign key (reviewer_id) references user_accounts (id);
alter table email_verification_tokens add constraint FK872kulygjhqf7678fxnbtlsi2 foreign key (user_account_id) references user_accounts (id);
alter table examples add constraint FKg09ahcdt5dlp6o2yp6m8ubbro foreign key (content_item_id) references content_items (id);
alter table examples add constraint FK9m2vfmkutab9vme0iskmmp4gd foreign key (meaning_id) references meanings (id);
alter table grammar_comparisons add constraint FK77unn3xjd8c8bj2w856lu91wc foreign key (grammar_relation_id) references grammar_relations (id);
alter table grammar_confirmation_attempts add constraint FK1a31u8ksjck8ipsltwuqyfplc foreign key (learner_profile_id) references learner_profiles (id);
alter table grammar_confirmation_attempts add constraint FKln25x7h4h039ojiol3egu1xr3 foreign key (question_id) references grammar_confirmation_questions (id);
alter table grammar_confirmation_choices add constraint FKsx4kso7pawhhp8w6xv772ae62 foreign key (question_id) references grammar_confirmation_questions (id);
alter table grammar_confirmation_questions add constraint FKe58m6rldnwyd7p8er7wo3774m foreign key (grammar_id) references grammars (id);
alter table grammar_enrichments add constraint FKj5jre5a2s0epc42swb77cng46 foreign key (grammar_id) references grammars (id);
alter table grammar_relations add constraint FKr0pv22sy3rs56sipcni99q86f foreign key (left_grammar_id) references grammars (id);
alter table grammar_relations add constraint FK4qccysgq4mbwxd7jho46vdkw2 foreign key (right_grammar_id) references grammars (id);
alter table grammars add constraint FK2xsuqultj9210mvj6u2vecwmc foreign key (content_item_id) references content_items (id);
alter table imported_source_records add constraint FKnm4e3iwcy3ri6fb3irybukops foreign key (content_item_id) references content_items (id);
alter table learner_preference_categories add constraint FKft82ob7a760ti4rq7ewu6q3j6 foreign key (preference_id) references learner_study_preferences (id);
alter table learner_preference_levels add constraint FKfym9g977sj6ho7h4e0493ep4s foreign key (preference_id) references learner_study_preferences (id);
alter table learner_profiles add constraint FKnrvqtu2xgwtb14wwe5kgvhhc8 foreign key (user_account_id) references user_accounts (id);
alter table learner_study_preferences add constraint FKa3nhny9kt4l0fpiyj6ud3lvlo foreign key (learner_profile_id) references learner_profiles (id);
alter table learning_progress add constraint FKi51u3eieq2esu575861ipgy61 foreign key (content_item_id) references content_items (id);
alter table learning_progress add constraint FK1ikmf1p3cpgpt7e5nlxfnif8w foreign key (learner_profile_id) references learner_profiles (id);
alter table learning_streaks add constraint FKfw1jbp69nsxyxdc8alvc8v9eu foreign key (learner_profile_id) references learner_profiles (id);
alter table meanings add constraint FKhn40i9go3lbmhyy9qslglsgq0 foreign key (word_id) references words (id);
alter table password_reset_tokens add constraint FKd0j8se7q4aahsqkngfrcu1l1r foreign key (user_account_id) references user_accounts (id);
alter table quiz_attempts add constraint FK3k8k4g1w85s5mrt0eoyplggy2 foreign key (learner_profile_id) references learner_profiles (id);
alter table quiz_session_items add constraint FKienn7eaju4yv8etywmaf2rnd9 foreign key (content_item_id) references content_items (id);
alter table quiz_session_items add constraint FKouo68qbvtxindj9sk43xwrhh9 foreign key (session_id) references quiz_sessions (id);
alter table quiz_sessions add constraint FKj3pxkrjjv4hyxc6qmpb1fwnxg foreign key (learner_profile_id) references learner_profiles (id);
alter table study_collection_items add constraint FKtf6oua1m4rriec9adj05l3lo7 foreign key (content_item_id) references content_items (id);
alter table study_collection_items add constraint FKar3dc77q11pir1ou4khnctl94 foreign key (study_collection_id) references study_collections (id);
alter table study_collections add constraint FK16enienb2e398mkm508x95yp8 foreign key (user_account_id) references user_accounts (id);
alter table study_queue_entries add constraint FKjsf7v019sj6t37240suw9ac7j foreign key (content_item_id) references content_items (id);
alter table study_queue_entries add constraint FKkbqvwntx5aef56ejqdtjlgmo4 foreign key (user_account_id) references user_accounts (id);
alter table study_records add constraint FKoyck277pg2elqqwtcesycclh2 foreign key (content_item_id) references content_items (id);
alter table study_records add constraint FKniddeg4en4906h40ra83g4oxi foreign key (learner_profile_id) references learner_profiles (id);
alter table today_study_session_items add constraint FKjs7u4a9ju6k4nvyvcg19iwdud foreign key (content_item_id) references content_items (id);
alter table today_study_session_items add constraint FKbo3ea5wrltq7jd2a3u0b3pxor foreign key (session_id) references today_study_sessions (id);
alter table today_study_sessions add constraint FKdstqk5sryapf8ck6fu6s8fa54 foreign key (learner_profile_id) references learner_profiles (id);
alter table weakness_review_session_items add constraint FK99ha1a2cpy7fr7u60dnj2yn73 foreign key (content_item_id) references content_items (id);
alter table weakness_review_session_items add constraint FK83qf5653eqoydxfm0eygy8yhx foreign key (session_id) references weakness_review_sessions (id);
alter table weakness_review_sessions add constraint FK9ux83r8sv81tm6dp76dlpeegj foreign key (learner_profile_id) references learner_profiles (id);
alter table words add constraint FKlv8egdrrugnkrtgjfrisbjles foreign key (content_item_id) references content_items (id);
