package com.japanese.content.entity;

public enum QualityIssueType {
    WORD_TEXT_BLANK,
    WORD_READING_BLANK,
    MEANING_MISSING,
    MEANING_BLANK,
    EXAMPLE_MISSING,
    EXAMPLE_TEXT_BLANK,
    EXAMPLE_TRANSLATION_BLANK,
    SOURCE_REF_MISSING,
    SOURCE_MISSING,
    JLPT_LEVEL_MISSING,
    DUPLICATE_WORD,
    DUPLICATE_GRAMMAR,
    MEANING_TOO_LONG,
    MARKUP_SUSPECTED,
    SURROUNDING_WHITESPACE,
    READING_TOO_LONG,
    GRAMMAR_PATTERN_BLANK,
    GRAMMAR_DESCRIPTION_BLANK,
    GRAMMAR_DESCRIPTION_TOO_SHORT,
    GRAMMAR_DESCRIPTION_TOO_LONG
}
