create table private_apkg_notes (
    id bigint generated by default as identity primary key,
    source_ref varchar(160) not null,
    source_file varchar(160) not null,
    source_version varchar(40) not null,
    source_note_id bigint not null,
    model_id bigint not null,
    note_type varchar(160) not null,
    category varchar(40) not null,
    anki_guid varchar(160) not null,
    deck_paths clob not null,
    card_metadata clob not null,
    tags clob not null,
    field_names clob not null,
    field_values clob not null,
    normalized_values clob not null,
    audio_reference_count integer not null,
    extracted_at timestamp(6) not null,
    constraint uk_private_apkg_note unique (source_ref, source_note_id)
);
create index ix_private_apkg_category on private_apkg_notes (source_ref, category);
